# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@4.7.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - node/test:
          app-dir: ~/project/backend
      - eb/deploy:
          app-dir: ~/project/backend
          context: aws-creds
          application-name: Project
          environment-name: project-env
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
          requires:
            - node/test
